### ISSUE TITLE
Buf::copy_to_bytes

### ISSUE THREAD

**Issue by stepancheg** [tokio-rs/bytes#129]
`Buf` could have `copy_to_bytes` operation:

```
fn copy_to_bytes(&mut self, len: usize) -> Bytes;
```

Default implementation should simply allocate new `Bytes`, while implementation for `Bytes` could call `slice`.

**Comment by vincentdephily** [comment]
I'd like this too. There's `Buf::to_bytes()` which consumes the remainder of the buffer, but that's rarely what we want. We need a `get_bytes()` like we need the other `get_*()`.

**Comment by mzabaluev** [comment]
Bikeshedding: `copy_to_bytes` does not sound true to what this method does (as far as I understand). Taking bytes from `self` should be emphasized, and maybe the potential for zero-copy implementation.

Maybe `extract_to_bytes`? I've got some prior art, though not as an intrinsic method: [`StrChunk::extract_utf8`](https://docs.rs/strchunk/0.2.0/strchunk/struct.StrChunk.html#method.extract_utf8)
