### ISSUE TITLE
Change From<&'a [u8]> to an explicit function

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/bytes#139]
Most of the `From` conversions to `Bytes` are shallow copies, just grabbing a pointer and pulling it in. There is also the `from_static` function to save copying a static set of bytes. However, the `From<&'a [u8]>` impl will copy the slice into a new buffer (either inline or a new heap allocation, depending on size). 

Unfortunately, that `&'a [u8]` means it applies to `&'static [u8]` as well. In cases where one is generic over `Into<Bytes>`, a user can easily and accidentally cause copies of static slices, instead of remembering to call `Bytes::from_static`. This issue proposes to change the defaults, so that **the faster way is easier**.

- Remove `From<&'a [u8]>` for `Bytes`/`BytesMut`.
- Add `From<&'static [u8]>` for `Bytes`/`BytesMut`.
- Add a new constructor that can take `&'a [u8]`, that explicitly shows a copy will happen.

The name of this new method could be a few things, these just some examples that occurred to me:

- `Bytes::copy(slice)`
- `Bytes::copy_from(slice)`

**Comment by seanmonstar** [comment]
Oh, this would be a breaking change, so would require (block?) 0.5.

**Comment by YetAnotherMinion** [comment]
Just to clarify, 

`From<&'a [u8]> for BytesMut` can stay because static slices are not mutable, so a copy has to happen from the  `'static`  slice when creating BytesMut.

So only Bytes would have its `From<&'a [u8]>` removed.

**Comment by carllerche** [comment]
Mentioned by @arthurprs:

> While I understand the reasoning this severely limits Byte as a Vec replacement, like backing a https://crates.io/crates/string

Specifically, this issue: https://github.com/carllerche/string/issues/6
