### ISSUE TITLE
Replace iovec with std::io::IoSlice

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/bytes#224]
This would allow avoiding the additional dependencies.

**Comment by archseer** [comment]
[IoVec was stabilised as IoSlice in 1.36](https://doc.rust-lang.org/nightly/std/io/struct.IoSlice.html), so we can probably drop the `iovec` dependency and use the std types.

**Comment by seanmonstar** [comment]
Yep, the plan with 0.5 is to switch to std's IoSlice.
