### ISSUE TITLE
Support zeroed allocations (e.g `reserve_zeroed`, `with_capacity_zeroed`)

### ISSUE THREAD

**Issue by 64** [tokio-rs/bytes#270]
Looking at instances of `unsafe` in reqwest, there are two places ([1](https://github.com/seanmonstar/reqwest/blob/564a08f23041edb5e7384e4a4d90accdef6b06c9/src/async_impl/decoder.rs#L207), [2](https://github.com/seanmonstar/reqwest/blob/964d87ce57fabf6b27d194adf36af25e4dc0d3b2/src/body.rs#L258)) where uninitialized memory is passed to a `Read` implementation. This is a *bad idea* (as per https://github.com/rust-lang/rust/pull/62102/files, https://gankro.github.io/blah/initialize-me-maybe/) and can be fixed by just zeroing the memory beforehand.

Unfortunately `bytes` doesn't provide a good way of doing this. I imagine the ideal solution would involve something that lowers to `alloc_zeroed` / `calloc` internally.

**Comment by Shnatsel** [comment]
FYI `vec![0; len];` lowers into `alloc_zeroed()` which just requests zeroed memory from the OS, so the allocating it is exactly as fast as requesting an uninitialized slice. 

See https://github.com/rust-lang/rust/issues/54628 for more details.

**Comment by Lokathor** [comment]
The zeroing takes about twice as long, but you should still do it to avoid UB because this is Rust.

**Comment by jocutajar** [comment]
I love how BytesMut works and would appreciate an initialized flavor as well. Or an interface to fill it from Read / AsyncRead safely.

**Comment by ldm0** [comment]
+1 For these methods. This would make creating a big zeroed `BytesMut` significantly faster.
