### ISSUE TITLE
BufMut: provide access to the written-to portions of the buffer(s)

### ISSUE THREAD

**Issue by sfackler** [tokio-rs/bytes#299]
When working with length-delimited protocols, it's often easiest to just serialize a message with a dummy length and then go back and fix it when you know what the final length is. This is possible when using `BytesMut` specifically since it provides mutable access to the written-to portion of the buffer, but not with a generic `BufMut`.

**Comment by carllerche** [comment]
Do you have an API suggestion? It may be that we need a separate trait?

**Comment by sfackler** [comment]
I think it'd look something like this:

```rust
pub trait BufMut {
    fn position(&self) -> usize;

    fn bytes_at_mut(&mut self, position: usize) -> &[u8];

    fn put_u8_at(&mut self, position: usize, v: u8) { ... }

    ...
}
```

It could be a separate trait, but it seems like it's a thing that could be supported without too much trouble with all of the existing implementations already.

**Comment by carllerche** [comment]
Consider BufList, a linked list of buffers. This type could not provide constant indexing. A position based api would be linear.

**Comment by sfackler** [comment]
Oh, sure. Any ideas on a trait name then? `BufMutRandomAccess`?

**Comment by carllerche** [comment]
Well, the thing is that you can still support the pattern for something like BufList. What you want to do is, as you are consuming the BufMut is to keep a handle to a chunk. I'm not 100% sure what the best model for that is.

**Comment by sfackler** [comment]
An associated `Position` type would cover that, but there might be GAT problems for something like BufList in particular. It would need to be able to step forward in the list.

**Comment by carllerche** [comment]
Is there a specific case you are trying to solve? Another option would be to take `T: BufMut + AsMut[u8]` (where the as_mut() returns data that has been written already).

**Comment by sfackler** [comment]
My specific use case is the Postgres backend protocol, which uses a lot of length-prefixed encodings: https://github.com/sfackler/rust-postgres/blob/master/postgres-protocol/src/message/frontend.rs#L13-L27

`BufMut + AsMut<u8>` is a good option though!

**Comment by carllerche** [comment]
Yeah, I hit that same issue in `h2` and ended up hard coding to `Bytes` / `BytesMut`.

I'm going to close the issue as I think `BufMut + AsMut<u8>` is the best option we have right now, but I  am happy to open it up again if there are new proposals.
