### ISSUE TITLE
Build issue: `core::slice::<impl [T]>::len` is not yet stable as a const fn

### ISSUE THREAD

**Issue by saschagrunert** [tokio-rs/bytes#323]
I encountered the following issue when building the crate via the stable toolchain:
```
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
   --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.0/src/bytes.rs:121:18
    |
121 |             len: bytes.len(),
    |                  ^^^^^^^^^^^
```
See: https://circleci.com/gh/saschagrunert/webapp.rs/13499?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by sfackler** [comment]
[T]::len is a const fn in 1.39. You need to update your Docker image (it's using whatever version was stable when it was published to the Docker hub).

**Comment by saschagrunert** [comment]
Ah alright thank you :+1:

**Comment by akshaykhale1992** [comment]
`rustup update stable` should fix the issue

**Comment by marcelo321** [comment]
`rustup update stable` didn't fix the issue for me :(

**Comment by Darksonn** [comment]
@marcelo321 If you receive this error, you are using an old compiler. If you did not install Rust with rustup, you need to update it using whatever other method you originally used to install Rust.

**Comment by ady624** [comment]
This fails for me with rustc 1.47.0, bytes 0.6.0, on darwin, cross compiling for target x86_64-unknown-linux-musl

**Comment by jinhale** [comment]
Running `rustup update` worked for me. 

`$ cargo --version
cargo 1.48.0 (65cbdd2dc 2020-10-14)`

**Comment by diaJalaeyRakhna** [comment]
I just encountered this same error. I ran
`rustup update` and `rustup update stable`
but `cargo --version` shows `cargo 1.38.0 (23ef9a4ef 2019-08-20)`
and `rustc --version` shows `rustc 1.38.0 (625451e37 2019-09-23)`

What to do?

**Comment by taiki-e** [comment]
> but `cargo --version` shows `cargo 1.38.0 (23ef9a4ef 2019-08-20)`
> and `rustc --version` shows `rustc 1.38.0 (625451e37 2019-09-23)`

I guess cargo installed by a way other than rustup is actually called. (like https://github.com/tokio-rs/tokio/issues/3355#issuecomment-751482243).
Could you try with toolchain override shorthand (`cargo +stable build`)?

**Comment by diaJalaeyRakhna** [comment]
Running `cargo +stable build` gives error `no such subcommand: +stable`

**Comment by diaJalaeyRakhna** [comment]
Running `rustup --version` gives following output:

> rustup 1.23.1 (3df2264a9 2020-11-30)
> info: This is the version for the rustup toolchain manager, not the rustc compiler.
> info: The currently active `rustc` version is `rustc 1.49.0 (e1884a8e3 2020-12-29)`
So how come running `rustc --version` still shows `rustc 1.38.0 (625451e37 2019-09-23)`??
This is really mind-boggling.

**Comment by taiki-e** [comment]
> Running `cargo +stable build` gives error `no such subcommand: +stable`

It seems cargo installed by a way other than rustup is called. I think it will work if you uninstall rust installed by the package manager, but it may not be easy if there are other packages that depend on the rust package.

**Comment by Darksonn** [comment]
Yeah, if you have Rust installed twice, the one provided by your package manager will typically take precedence over the one provided by rustup.

**Comment by diaJalaeyRakhna** [comment]
> I guess cargo installed by a way other than rustup is actually called. (like [tokio-rs/tokio#3355 (comment)](https://github.com/tokio-rs/tokio/issues/3355#issuecomment-751482243)).
> Could you try with toolchain override shorthand (`cargo +stable build`)?

@taiki-e: You were right. I had installed Windows version of rust some 2 years back and didn't remember. Referenced post helped. I just uninstalled `Rust 1.38 MSVC` from `Programs and Features` and just by uninstalling, running `rustc --version` showed `rustc 1.49.0 (e1884a8e3 2020-12-29)` and my program (and bytes crate) got compiled.

Thanks a bunch!
