### ISSUE TITLE
Consider renaming `IoSliceMut` to something implying MaybeUninit

### ISSUE THREAD

**Issue by Kixunil** [tokio-rs/bytes#332]
It's great to see that the same mistake as in the case of `bytes_mut` wasn't made in `IoSliceMut`, but it does look at the first sight that it was. :) I guess that could be confusing for users of the crate. `IoSliceMaybeUninitMut` or `IoSliceUninitMut` would be clearer.

**Comment by seanmonstar** [comment]
Considered that 😭 https://twitter.com/seanmonstar/status/1187095905020694528

Figured the longer name didn't make it any safer, and the exposed API was clear enough.

**Comment by Kixunil** [comment]
I agree that it's not related to safety. Just that people will probably try to shove in the type from `std` instead of from `bytes`. And if there's anyone sceptical like me, he will waste time analyzing if it's actually safe. :rofl:

**Comment by carllerche** [comment]
`IoSliceMut` has been removed.
