### ISSUE TITLE
`impl From<BytesMut> for Bytes` was removed

### ISSUE THREAD

**Issue by tmccombs** [tokio-rs/bytes#345]
It appears that commit 43ac8e5494e9404327f971937edb092b8cae6a2b removed the implementation of `From<BytesMut>` for `Bytes`.  This removal was not mentioned in the changelog.

Was this removal intentional? And if so, what was the reasoning for it?

**Comment by JJJollyjim** [comment]
Ran into this while upgrading - it sounds like it was intentional, from the commit message you linked:

> Removed `Bytes` knowledge of `BytesMut` (`BytesMut` may grow that
  knowledge back at a future point.)

**Comment by carllerche** [comment]
Hmm... I *think* it should be fine to add a conversion from `BytesMut` -> `Bytes`. That conversion can always stay paired w/ the `BytesMut` implementation.

Thoughts @seanmonstar?

**Comment by tmccombs** [comment]
fwiw the old implementation just called `BytesMut::freeze`

**Comment by seanmonstar** [comment]
Sure, we can it in `bytes_mut.rs` file.

**Comment by seanmonstar** [comment]
Fixed by #348.
