### ISSUE TITLE
bytes::buf::ext::{Reader,Writer} have broken links in their docs

### ISSUE THREAD

**Issue by Arnavion** [tokio-rs/bytes#353]
https://github.com/tokio-rs/bytes/blob/39b6646e669a35d40e0da8e582b234226f024cae/src/buf/ext/reader.rs#L8
https://github.com/tokio-rs/bytes/blob/39b6646e669a35d40e0da8e582b234226f024cae/src/buf/ext/writer.rs#L8

These are 404, eg https://docs.rs/bytes/0.5.3/bytes/buf/ext/trait.Buf.html#method.reader

`trait.Buf.html` should be `trait.BufExt.html` and `trait.BufMut.html` should be `trait.BufMutExt.html`

**Comment by taiki-e** [comment]
Closing -- fixed (https://docs.rs/bytes/1.0.1/bytes/buf/struct.Reader.html, https://docs.rs/bytes/1.0.1/bytes/buf/struct.Writer.html)
