### ISSUE TITLE
[Question] About zero copy codec impl?

### ISSUE THREAD

**Issue by najamelan** [tokio-rs/bytes#369]
I have a implementation of Encoder, which has the signature:

```rust
fn encode( &mut self, item: Self::Item, buf: &mut BytesMut ) -> Result<(), Self::Error>
```
Where `Self::Item` basically is `Bytes`. In the encoder I have to prefix it with the length of the Bytes, so the decoder on the other end knows how many bytes to read before the message is complete. So now I do:

```rust
buf.put_u64_le( length );
buf.put( item );
```
I suppose that here `put` will copy the bytes into buf. Is there a way to do this without copying? I could include the length field inside the item I suppose, but the API still requires me to put it in the `&mut BytesMut` I receive.

**Comment by najamelan** [comment]
If I feed it in as a `BytesMut`, can I use `std::mem::swap`? Or does that cause problems if it's not the same buffer?

**Comment by seanmonstar** [comment]
The stuff in `tokio-codec` is designed for *ease of use*. If you wanted to prevent copying the `Bytes`, I'd recommend handling encoding onto the connection yourself, and using some `BufQueue` type that holds the header and body.

As for `mem::swap`ping on the `BytesMut`, I can't easily comment on if that's a good idea. It might be that a previous message is still in the buffer waiting for to flushed, and you could be tossing it.

**Comment by najamelan** [comment]
thanks for the hints, I'll look into that.
