### ISSUE TITLE
Feature: Consider providing `StrBytes` interface

### ISSUE THREAD

**Issue by Diggsey** [tokio-rs/bytes#373]
This would act like the `Bytes` object but would guarantee that the contents are valid utf-8. It would not implement `Buf` but would deref to `&str` and have conversions to the `String` type.

There would be `TryFrom/TryInto` conversions from `Bytes` to `StrBytes` which would scan the string for validity but would not copy it. There would be zero-cost `From/Into` conversions from `StrBytes` to `Bytes`. There would be an unsafe zero-cost conversion method from `Bytes` to `StrBytes` for when the bytes are already known to be valid.

It would be convenient (but not essential) if there was a way to general substring-returning operations on a `StrBytes` that themselves returned a `StrBytes`.

This would enable zero-copy string deserialization in the same way as for raw bytes.

**Comment by carllerche** [comment]
Does something like this work? https://docs.rs/string/0.2.1/string/

**Comment by Diggsey** [comment]
Yes. 👍

**Comment by stackinspector** [comment]
The `String<T>` in the crate `string` has no serde support implementation. When I tried to implement support for serde, I found that not knowing whether the internal bytes are borrowed or owned or something like `Bytes` could lead to additional overhead during deserialization. It would be much easier to implement serde support if a wrapper was created on a _deterministic_ `Bytes`.

**Comment by Darksonn** [comment]
The `bytestring` crate provides serde support.
