### ISSUE TITLE
`get_bytes` for `Buf` trait

### ISSUE THREAD

**Issue by Diggsey** [tokio-rs/bytes#374]
`fn get_bytes(&mut self, size: usize) -> Bytes`

This is somewhat similar to https://github.com/tokio-rs/bytes/issues/228 but for reading from a `Buf`.

The idea is that a `Buf` implementation may already have an efficient way to get a "view" of some of its bytes that does not involve an expensive copy. The default implementation would just allocate a new `Bytes` object and then use `copy_to_slice`.

The `Bytes` type could have a specialized implementation that just calls `split_to` on itself. In the future it may be possible to specialize the implementation of `Buf` for `&'static [u8]` too, since `Bytes` can cope with that, or maybe `Bytes` will get an optional lifetime parameter allowing it to hold reference of any lifetime.

**Comment by danburkert** [comment]
I think this is fixed by #439.

**Comment by Diggsey** [comment]
Yep 👍
