### ISSUE TITLE
Could not compile `bytes`

### ISSUE THREAD

**Issue by hosseind2** [tokio-rs/bytes#379]
<img width="802" alt="Screen Shot 2020-03-23 at 8 23 55 PM" src="https://user-images.githubusercontent.com/57390535/77335772-3a355980-6d44-11ea-95d1-4eb968efcb24.png">

**Comment by sfackler** [comment]
You need to upgrade your Rust version.

**Comment by hosseind2** [comment]
it worked, thanks
