### ISSUE TITLE
bytes fails to compile on stable rust?

### ISSUE THREAD

**Issue by matthiasbeyer** [tokio-rs/bytes#380]
bytes seems to be a dependency of one of my dependencies (or worse...) and seems to fail to compile on stable rust.

My change that triggered this for me: https://github.com/matthiasbeyer/imag/commit/b163496d6d56af303c4b0cc79a1eb825d560d023 updates the "mdcat" crate which is one of my dependencies.

The error: https://travis-ci.org/github/matthiasbeyer/imag/jobs/666421537 

For the lazy:

```
   Compiling bytes v0.5.4

error: `core::slice::<impl [T]>::len` is not yet stable as a const fn

   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:130:18

    |

130 |             len: bytes.len(),

    |                  ^^^^^^^^^^^

error: aborting due to previous error
```

although bytes does not seem to be a direct dependency of mdcat: https://github.com/lunaryorn/mdcat/blob/master/Cargo.toml

Can you help me to figure out what's wrong?

**Comment by Ralith** [comment]
Your rustc needs to be updated; see https://github.com/tokio-rs/bytes/issues/379.
