### ISSUE TITLE
Implement io::Read for Bytes

### ISSUE THREAD

**Issue by kornelski** [tokio-rs/bytes#386]
I can't find a zero-cost way to pass `Bytes` to a function that wants `impl std::io::Read`.

There's a note in the documentation about relationship to `io::Read`, but I don't understand what it is trying to say.

Currently to get a `Read`er, I need to do `&mut bytes.to_vec().as_slice()` (using `impl Read for &[u8]`). I'd prefer to pass something like `bytes.cursor()` or `&mut bytes` that can satisfy read requests without converting `bytes` first.

**Comment by carllerche** [comment]
Does this work? https://docs.rs/bytes/0.5.4/bytes/buf/ext/trait.BufExt.html#method.reader

**Comment by kornelski** [comment]
Thanks! I somehow missed that.
