### ISSUE TITLE
Tokio dependency error - Bytes

### ISSUE THREAD

**Issue by hanusek** [tokio-rs/bytes#390]
``cargo build --release` -> Error
``cargo build` -> OK

```
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
    --> /home/gitlab-runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:130:18
     |
 130 |             len: bytes.len(),
     |                  ^^^^^^^^^^^
```

cargo 1.43.0 (2cbe9048e 2020-05-03) - stable

**Comment by seanmonstar** [comment]
This error is from having an older `rustc`.

**Comment by hanusek** [comment]
> This error is from having an older `rustc`.

rustc 1.43.1 (8d69840ab 2020-05-04)
old?

**Comment by seanmonstar** [comment]
No, that's a recent compiler. I'm just saying the error is from an old compiler. The `bytes` crate compiles at least on Rust 1.39 or greater. I don't know why your system might be using one, maybe a `rustup override` or something?
