### ISSUE TITLE
Name of Buf::to_bytes does not follow self conventions

### ISSUE THREAD

**Issue by mzabaluev** [tokio-rs/bytes#398]
An inherent method with the signature of `Buf::to_bytes` would not pass clippy:

> methods called `to_*` usually take self by reference; consider choosing a less ambiguous name
> help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention

In the next breaking release, consider renaming the method or maybe replace it with #129 (though less deceptively named than `copy_to_bytes`).

**Comment by seanmonstar** [comment]
Hm, it is true it doesn't follow that convention (though I don't think that's too big a deal in itself). I don't think of any convenient other names that explain what it does. Possibly something like `take_bytes` or `take_into_bytes`
...

**Comment by taiki-e** [comment]
Fixed by #439
