### ISSUE TITLE
Loom should be dev dependency

### ISSUE THREAD

**Issue by JordiPolo** [tokio-rs/bytes#400]
Bytes brings as dependency loom which itself brings a lot of stuff. This is very surprising because loom is a testing utility.

**Comment by seanmonstar** [comment]
It's listed only for `cfg(loom)`.

**Comment by Ralith** [comment]
Does that actually work?

**Comment by JordiPolo** [comment]
I'm getting bytes via reqwest and tokyo, no extra configuration or anything and I do get loom

**Comment by jplatte** [comment]
@JordiPolo Can't reproduce. Creating a dummy project and adding `tokio` with `features = ["full"]` + `reqwest`, then running `cargo tree`, does not turn up `loom`.

**Comment by JordiPolo** [comment]
Maybe is my ignorance of how Cargo works then.
Indeed `cargo tree` does not show `loom` but it is in the `Cargo.lock` file as dependency of `bytes`

**Comment by jplatte** [comment]
With my dummy project it also wasn't compiled. I'm pretty sure the lockfile is target-independent, so compiling the same project for different targets doesn't change the lockfile back and forth (if it would that would be very annoying for applications that keep the lockfile in source control).

**Comment by jplatte** [comment]
crates.io could really use some UI for target-specific dependencies though...

**Comment by JordiPolo** [comment]
Yeah, just looking at the files in my repo I do not have enough information to know if I am going to compile this into my production application which can be scary. 
Anyways, this turned out to not be an issue, thank you for looking into it!

**Comment by benma** [comment]
Please reopen this issue. It is also a problem when using `cargo vendor`, which pulls in a ton of crates that should not be there.

**Comment by jplatte** [comment]
Seems like something that should be handled as an option in `cargo vendor`, like `cargo metadata`s `--filter-platform` or `cargo tree`s `--target`.

**Comment by benma** [comment]
> Seems like something that should be handled as an option in `cargo vendor`, like `cargo metadata`s `--filter-platform` or `cargo tree`s `--target`.

Would be nice, but I don't think it exists? See also https://www.reddit.com/r/rust/comments/8plauq/dont_vendor_deps_i_dont_need/

**Comment by jplatte** [comment]
Doesn't look like it but still, if the extra stuff being downloaded is an issue for you, you should probably try to get cargo fixed rather than having bytes work around it. The main issue seems to be https://github.com/rust-lang/cargo/issues/4544.

**Comment by benma** [comment]
I agree in principle, but in theory it could take years to fix it in cargo. Maybe there is a simple workaround in `bytes` that could help in the meantime.

In any case, the solution I went for in the end is to fork `bytes`, remove the `loom` dep, and patch it in with a `[patch]` section in my `Cargo.toml`. It's not great, especially as I need to maintain the fork and keep it in sync with new releases.

**Comment by carllerche** [comment]
Switching it to a `dev-dependency` should be a trivial PR. Anyone here should feel free to submit it.
