### ISSUE TITLE
Consider add inline attribute `BytesMut::set_len`

### ISSUE THREAD

**Issue by botika** [tokio-rs/bytes#407]
inline `set_len` call translates to assembler:
```asm
add     qword, ptr, [rsp, +, 8], LEN
```
It is much less instructions than preparing the registers for the call:
```asm
mov     rsi, qword, ptr, [rsp, +, 8]
add     rsi, LEN
mov     rdi, rsp
call    qword, ptr, [rip, +, _ZN5bytes9bytes_mut8BytesMut7set_len17h54d98ffd051013e5E@GOTPCREL]
```
The assembler generated with the inline attribute is https://github.com/botika/buf-min/blob/master/benches/README.md from  https://github.com/botika/buf-min/blob/master/benches/src/main.rs

**Comment by seanmonstar** [comment]
Sounds good and simple, want to make a PR?
