### ISSUE TITLE
loom dependency pulled in by default

### ISSUE THREAD

**Issue by djc** [tokio-rs/bytes#411]
Since #392 (by @taiki-e), it looks like loom went from a dev-dependency to a default dependency. It's guarded by `cfg(loom)`, but I'm not sure if that's working as intended. My application now seems to be pulling in loom as a dependency of `bytes` even though I didn't specify any `loom` cfg. As far as I understand, loom should only be used for testing?

**Comment by djc** [comment]
Ah, sorry, I got confused by cargo update calling this out, but it doesn't look like this gets built without `--cfg loom` enabled. It just clutters up `Cargo.lock` files, which had me confused for a moment.

**Comment by taiki-e** [comment]
Yeah, cargo writes all `target.cfg(..).dependencies` to Cargo.lock even if it never activates (this is the same as `target.cfg(windows)`, `target.cfg(unix)`, etc.). But unless you set `RUSTFLAGS`, they will never actually be compiled.

Also, `target.cfg(..).dependencies` are basically supported except `cfg(feature = ..)`, `cfg(test)`, etc (see https://github.com/rust-lang/cargo/pull/7660#issuecomment-561733620)
