### ISSUE TITLE
Undefined Behavior: incorrect layout on deallocation, at `BytesMut.advance()` and `Bytes.advance()`

### ISSUE THREAD

**Issue by botika** [tokio-rs/bytes#422]
Just running `cargo miri test`. Moving the pointer does not dealloc it correctly, producing UB. 
```rust
let mut buf: Bytes = vec![0u8; 8].into();
buf.advance(2);
drop(buf);
```
Should dealloc when advance it as it will not be used again.

**Comment by Darksonn** [comment]
Can you provide the full main function you used?

**Comment by botika** [comment]
With coverage

**Comment by Darksonn** [comment]
It does not appear to fail on the playground when you choose miri in the tools on the following:
```rust
use bytes::{Bytes, Buf};

fn main() {
    let mut buf: Bytes = vec![0u8; 8].into();
    buf.advance(2);
    drop(buf);
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=725397900af3557a45e49e4d4faaf2ca)

What did you do to reproduce this?

**Comment by botika** [comment]
It's my fault, I close.
