### ISSUE TITLE
StableDeref for Bytes?

### ISSUE THREAD

**Issue by flub** [tokio-rs/bytes#426]
I would like to store `Bytes` as the owning type in a rental `RentRef` struct (https://docs.rs/rental/0.5.4/rental/common/struct.RentRef.html) but for this `Bytes` needs to implement the `StableDeref` marker trait (https://docs.rs/stable_deref_trait/1.2.0/stable_deref_trait/trait.StableDeref.html).

`StableDeref` is implemented for `Vec<T>` and IIUC `Bytes` uses `Vec<u8>` as underlying type so this should be allowed as it guarantees that `Bytes` will always be heap allocated.  Would it be possible to implement this trait, or perhaps as an optional feature?  Or is there a reason this should not be done?

The current work-around is to give the referring type a `static` lifetime but it would be nice not to need to do this.

**Comment by seanmonstar** [comment]
I wouldn't want to add such a public dependency (breaking changes there force them here to upgrade).

**Comment by sunny-g** [comment]
@seanmonstar perhaps as an optional dependency/behind a feature flag? :pray:

**Comment by sunny-g** [comment]
I'd like to second this (if applicable to `Bytes`), if for no other reason than the StableDeref maintainers don't want to implement the trait for non-std types: https://github.com/Storyyeller/stable_deref_trait/issues/12.

**Comment by carllerche** [comment]
We are not going to add dependencies on non-std types either. The strategy here would be to implement a `StableBytes` wrapper.
