### ISSUE TITLE
Why does Option<[u8; 1]> implement Buf?

### ISSUE THREAD

**Issue by xfix** [tokio-rs/bytes#444]
`Buf` trait has a rather curious implementation for `Option<[u8; 1]>` which was introduced in https://github.com/tokio-rs/bytes/pull/72. I don't think it's particularly useful and currently there are no tests of it working to begin with (if I remove this implementation which has no doc comments the tests still pass). I think it could be removed in 1.0 (or 0.7 I suppose).

**Comment by seanmonstar** [comment]
I see very little value in the implementation. I'd be fine with removing it.

**Comment by Darksonn** [comment]
It seems to have been used for an `impl IntoBuf for u8`, but I'm not sure `IntoBuf` still exists?

**Comment by xfix** [comment]
`IntoBuf` doesn't exist, but even if it did, I think it would have made more sense to use [`std::slice::from_ref`](https://doc.rust-lang.org/std/slice/fn.from_ref.html).
