### ISSUE TITLE
Convenience wrapper for buf.take(len).copy_to_bytes(len)

### ISSUE THREAD

**Issue by djc** [tokio-rs/bytes#455]
This would be nice to have, since `Buf::bytes()` no longer returns all of remaining getting this right is a bit cumbersome now.

**Comment by Darksonn** [comment]
> since `Buf::bytes()` no longer returns all of remaining

This was never the case. The name was just updated to `chunk` to make it more clear that it might not return all of the remaining data.

**Comment by djc** [comment]
Never mind, I have to check the bounds anyway, so there's not much point in this.
