### ISSUE TITLE
1.0.x renamed bytes to chunk and bytes_mut to chunk_mut

### ISSUE THREAD

**Issue by jocutajar** [tokio-rs/bytes#470]
Hi, The 1.0.x major release renamed bytes() to chunk() and bytes_mut() to chunk_mut()

This move was really confusing. No hint in the change log, no deprecation notice, just pufff... broken code, now what? If nothing else, this issue may lead others to the correct new names. I do get that it is the first major release and breaking changes should be expected. Still it was a bit disturbing.

* Please add a note to docs about this change.
* Can you add retrospectively to the change log?
* I wonder what would be the value adding bytes / bytes_mut back with deprecation notice?

This will help others understand the change and update their code with confidence.

**Comment by seanmonstar** [comment]
The changelog does mention it: https://github.com/tokio-rs/bytes/blob/master/CHANGELOG.md#100-december-22-2020

As a "required" trait method, we can't really include it with a deprecated attribute.

**Comment by jocutajar** [comment]
Oky, @seanmonstar , now I see it:
```
Rename Buf/BufMut, methods to chunk/chunk_mut (#450)
```
I explicitly looked for bytes and bytes_mut. May I suggest:
```
Rename Buf/BufMut methods bytes() and bytes_mut() to chunk() and chunk_mut() (#450)
```

**Comment by jocutajar** [comment]
Re "required" - I think you could:
```
trait Old { 
    fn old (&self);
}

trait New { 
    #[deprecated(since = "1.0.2", note = "Use new() instead")]
    fn old (&self) { self.new() }
    fn new (&self);
}
```

**Comment by Darksonn** [comment]
I think adding a deprecated version back to the trait is a really bad idea. When using `#[deprecated]`, it should have been in version 0.6, marking it as deprecated _there_, then removing it with the breaking change.

We can add a doc alias so `chunk_mut` shows up when you search for `bytes_mut` in the documentation. Adding the word `bytes_mut` to the changelog so it shows up with ctrl+f would probably also be fine.

**Comment by carllerche** [comment]
Feel free to open a PR to tweak the changelog. We are not going to add a deprecated trait method as those are problematic.
