### ISSUE TITLE
Opportunistic optimization of copy_to_bytes on Take and Chain

### ISSUE THREAD

**Issue by vorner** [tokio-rs/bytes#475]
The `copy_to_bytes` method allows optimizing it by slicing a `Bytes` instead of copying, which is implemented for `Bytes` itself. The default implementation, however, copies things, while it might be possible to delegate into the inner implementation that might be `Bytes`, and therefore sometimes gain this optimization too.

It should be pretty simple for `Take` (just limit to whatever the current limit is, then call the inner `copy_to_bytes`). The `Chain` has two cases, one that fits into the current buffer and can delegate, and another that is across the boundary that needs to copy, which is a bit more involved.

What I'm asking, is there a good reason why these should not be implemented, or can I submit a pull request adding them?

**Comment by Darksonn** [comment]
A specialized implementation for those seems fine.

**Comment by taiki-e** [comment]
done in #481
