### ISSUE TITLE
How to make a reverse bytes?

### ISSUE THREAD

**Issue by awsa2ron** [tokio-rs/bytes#520]
Hi,

I need a reverse bytes, which is back off not advance. What should I do? Implement a new struct with three required methods and those functions and Vtables again? 

Thanks.

**Comment by Darksonn** [comment]
I don't understand the question.

**Comment by overheat** [comment]
I need this: hello -> hell -> hel -> he -> h

**Comment by overheat** [comment]
I think it means this: hello -> hell -> hel -> he -> h
