### ISSUE TITLE
`Bytes::with_vtable` Can it be opened for external use

### ISSUE THREAD

**Issue by xiaxiangjun** [tokio-rs/bytes#526]
Just want to use it to use shared memory, but it `pub(crate) unsafe fn with_vtable` and `pub(crate) struct Vtable`, Hope to change to remote `(crate)`

**Comment by xiaxiangjun** [comment]
path: `src/bytes.rs:102`

```rust
pub(crate) struct Vtable
// Change to
pub struct Vtable
```

path: `src/bytes.rs:478`

```rust
pub(crate) unsafe fn with_vtable
// Change to
pub unsafe fn with_vtable
```

path: `src/lib.rs:92`

```rust
// add
pub use crate::bytes::Vtable;
```

**Comment by NobodyXu** [comment]
Why not open a PR then?

**Comment by seanmonstar** [comment]
It is an eventual goal to make it public, but there are unresolved questions around forwards-compatibility.

- Is the current vtable all the functions that are needed?
- If we identify a new function later, how can we add it to the vtable without breaking people?

**Comment by Darksonn** [comment]
Closing as duplicate of #437.
