### ISSUE TITLE
How to convert `[u8; _]` to `Bytes`?

### ISSUE THREAD

**Issue by stackinspector** [tokio-rs/bytes#536]
when I try to call `Bytes::from` on `[u8; 32]` as an example, I get that From<[u8; 32]> is not implemented. If I add `.as_slice()`, I get that the source does not live long enough. Adding `Box::new`, I get that From<Box<[u8; 32]>> is also not implemented. And converting to `Vec` is bound to have overhead. So how to properly convert `[u8, _]` to `Bytes`?

**Comment by Darksonn** [comment]
You can do `Bytes::copy_from_slice(&your_array)`.
