### ISSUE TITLE
Faillably get data from the `Buf`  

### ISSUE THREAD

**Issue by midnightexigent** [tokio-rs/bytes#537]
currently the methods that read data from the underlying buffer panic if no more data can be read. this behavior is kind of annoying because it feels awkward to manually check before reading.

```rs
// this is awkward
if buf.remaining() < 2 {
    Err(UnexpectedEof)
} else {
    Ok(buf.get_i16())
}
```

so far 2 PRs have tried to implement a fallible way to read data from `Buf` (`try_get_*()`), but weren't merged

is there any intention to support this use case in the near future ?

**Comment by ten3roberts** [comment]
The h3 crate uses the same approach as mentioned implemented as another trait. As stated it would be a lot more ergonomic if a fallible read trait of functions were upstreamed into Bytes
