### ISSUE TITLE
BytesMut remaining

### ISSUE THREAD

**Issue by snaggen** [tokio-rs/bytes#582]
I tried to use BytesMut but the remaining() didn't work as I expected. I basically expected it to be `buf.capacity() - buf.len()`.
However in the implementation for BytesMut i find this code
```
    #[inline]
    fn remaining(&self) -> usize {
        self.len()
    }
```
Which looks like a bug since the documentation for remaining() in Buf says
>Returns the number of bytes between the current position and the end of the buffer.
>
>This value is greater than or equal to the length of the slice returned by chunk().

**Comment by Darksonn** [comment]
The `Buf` trait is for _reading_ data out of the buffer. The size of the uninitialized region is irrelevant for that. The implementation is correct.
