### ISSUE TITLE
Missing way to create Bytes from a slice of Bytes

### ISSUE THREAD

**Issue by xfbs** [tokio-rs/bytes#604]
Hey!

I want a way to turn a slice (`&[u8]`) of a `Bytes` back into a `Bytes` without having to go `slice.to_vec().into()`. 

For context: I'm using the `Bytes` crate in the [diff.rs](https://github.com/xfbs/diff.rs) project. In there I'm using the `similar` crate to produce a diff. It does not natively support `Bytes`, but it does support taking two `&[u8]` as input and producing an iterator of changed lines (as `&[u8]`). Now, I know that these slices all point into the original `Bytes`, and so to process them further I want to turn these slices back into `Bytes` that I can store and send around. Example:

```rust
let bytes: Bytes = Bytes::from_static(b"some data");
// this method currently exists
let bytes_slice: Bytes = bytes.slice(1..6);

// this method is what I would like
let slice: &[u8] = &bytes[1..6];
let slice_bytes: Bytes = bytes.from_slice(slice).unwrap();
```

Right now, I'm doing this with a little hack using the `subslice-offset` crate, which lets me get the offset of two slices so that I can then call `Bytes::slice`. But it would be nice to have this built-in to the library, maybe other people run into the same issue, when working with libraries that only support slices but you would like to use `Bytes` with zero-copy.

**Comment by Darksonn** [comment]
Haha, we already have this feature? I didn't even know. Closing this as duplicate.
