### ISSUE TITLE
An arithmetic overflow bug found by afl.rs

### ISSUE THREAD

**Issue by Koral77** [tokio-rs/bytes#609]
I've using [afl.rs](https://github.com/rust-fuzz/afl.rs) to fuzz this crate. And I've found an API may panic due to arithmetic overflow.
The code to replay this panic is
```
unsafe {
    let mut _local0 = bytes::BytesMut::zeroed(134217983);
    bytes::buf::BufMut::advance_mut(&mut (_local0), 18446744073707388928);
}
```
The bug report is
![image](https://user-images.githubusercontent.com/58699405/229962697-36bccb7d-196d-4015-b040-8f35eb7abb85.png)
I hope you can check if this is a real bug need to be fixed. Thanks a lot.

**Comment by sfackler** [comment]
https://docs.rs/bytes/latest/bytes/trait.BufMut.html#panics
