### ISSUE TITLE
make Bytes repr(C)?

### ISSUE THREAD

**Issue by dovahcrow** [tokio-rs/bytes#610]
I find it useful if Bytes is `#[repr(C)]` so it can pass through the FFI boundary. BytesMut cannot since it has `Vec` in it, but Bytes seems to be safe to `#[repr(C)]`. I have the little patch here: https://github.com/dovahcrow/bytes/commit/6ac9e4bb2a7b1084f7721813ffc7b816253cc4b5 and I can PR if the team wants.

**Comment by Darksonn** [comment]
This has serious backwards compatibility challenges. I'm not ready to freeze the representation forever.

**Comment by dovahcrow** [comment]
I see, no worries. Shall we close this issue now?
