### ISSUE TITLE
There is no Bytes::advance

### ISSUE THREAD

**Issue by Garmelon** [tokio-rs/bytes#621]
The `must_use` warning on `Bytes::split_to` suggests using `Bytes::advance` if you don't need the returned value. However, that function is private since d8134903de1be93227ce376e1fb640ac2acfa8c1.

It would be nice to be able to write `buf.advance(n)` instead of `let _ = buf.split_to(n)`.

**Comment by Walnut356** [comment]
`advance` is part of trait `Buf`, and is implemented on `Bytes` [here](https://github.com/tokio-rs/bytes/blob/master/src/bytes.rs#L548). Traits are always public, so as long as `use bytes::Buf;` is in scope, you should be able to `buf.advance(n)` as you described.
