### ISSUE TITLE
Why is the `data` pointer atomic?

### ISSUE THREAD

**Issue by RalfJung** [tokio-rs/bytes#623]
I've been trying to understand how bytes works these days, and one thing I cannot figure out is: why is the [data pointer](https://github.com/tokio-rs/bytes/blob/05e9d5cab95e5ce1d57dd498a9567639de50f841/src/bytes.rs#L104) atomic? So far I've only found calls to `data.load` and `data.with_mut`, but I could not find a case where it is actually mutated while shared. Grepping for `data.store` comes back empty.

**Comment by Darksonn** [comment]
I believe it's here:

https://github.com/tokio-rs/bytes/blob/05e9d5cab95e5ce1d57dd498a9567639de50f841/src/bytes.rs#L1157-L1166

**Comment by RalfJung** [comment]
Ah, that's it indeed! Thanks.
