### ISSUE TITLE
How to use uninitialized BytesMut?

### ISSUE THREAD

**Issue by surban** [tokio-rs/bytes#638]
Hi!

When using a plain `Vec<_>` I can create it with `Vec::with_capacity`, initialize the memory externally and then use `Vec::set_len` as shown by this [example](https://doc.rust-lang.org/std/vec/struct.Vec.html#examples-22). 

Is the same pattern valid for `BytesMut`? It seems so, but I could not find any guarantee in the documentation.

Thanks.

**Comment by Darksonn** [comment]
Yes, this is possible. If you use the `advance_mut` and `chunk_mut` methods from the [`BufMut`](https://docs.rs/bytes/latest/bytes/buf/trait.BufMut.html) trait, then you get the desired behavior.

**Comment by surban** [comment]
Is using `as_mut_ptr` followed by `set_len` from `BytesMut` also valid?

**Comment by Darksonn** [comment]
> Is using as_mut_ptr followed by set_len from BytesMut also valid?

Yes.
