### ISSUE TITLE
Potential to modify ordering for load in bytes.rs and bytes_mut.rs

### ISSUE THREAD

**Issue by wang384670111** [tokio-rs/bytes#648]
I developed a static analysis tool to detect issues related to memory ordering, thread performance, and security. During my examination of several crates, I encountered alarms triggered by the following code：
https://github.com/tokio-rs/bytes/blob/74e6e200fd671340d4d4a874f83776def04f6c7b/src/bytes.rs#L1096
https://github.com/tokio-rs/bytes/blob/74e6e200fd671340d4d4a874f83776def04f6c7b/src/bytes.rs#L1066-L1093
`Relaxed` at 1096 is weak because `data` is dereferenced at 1073. We should use `Acquire` to observe other modifications made to this location. Therefore, I believe that the load operation for the head should use `Acquire`. Similar issues appears in the code below:
https://github.com/tokio-rs/bytes/blob/74e6e200fd671340d4d4a874f83776def04f6c7b/src/bytes.rs#L1062-L1063
https://github.com/tokio-rs/bytes/blob/74e6e200fd671340d4d4a874f83776def04f6c7b/src/bytes.rs#L1105-L1118

The above is also used in bytes_mut.rs, `data` is dereferenced with `Relaxed`:
https://github.com/tokio-rs/bytes/blob/74e6e200fd671340d4d4a874f83776def04f6c7b/src/bytes_mut.rs#L1721-L1723

https://github.com/tokio-rs/bytes/blob/74e6e200fd671340d4d4a874f83776def04f6c7b/src/bytes_mut.rs#L1713-L1714
https://github.com/tokio-rs/bytes/blob/74e6e200fd671340d4d4a874f83776def04f6c7b/src/bytes_mut.rs#L1337-L1343

**Comment by Darksonn** [comment]
All of the codepaths you have pointed out are reachable only when the vtable is `SHARED_VTABLE`. However, when this is the case, the `data` field is immutable and never modified. Therefore, relaxed is enough. In fact, a non-atomic load would have been enough.

To see this, note that the `data` pointer is only changed in one location:

https://github.com/tokio-rs/bytes/blob/74e6e200fd671340d4d4a874f83776def04f6c7b/src/bytes.rs#L1157-L1166

However, that line of code is only callable on a `Bytes` or `BytesMut` if the vtable is `PROMOTABLE_EVEN_VTABLE` or `PROMOTABLE_ODD_VTABLE`.

**Comment by wang384670111** [comment]
> All of the codepaths you have pointed out are reachable only when the vtable is `SHARED_VTABLE`. However, when this is the case, the `data` field is immutable and never modified. Therefore, relaxed is enough. In fact, a non-atomic load would have been enough.
> 
> To see this, note that the `data` pointer is only changed in one location:
> 
> https://github.com/tokio-rs/bytes/blob/74e6e200fd671340d4d4a874f83776def04f6c7b/src/bytes.rs#L1157-L1166
> 
> However, that line of code is only callable on a `Bytes` or `BytesMut` if the vtable is `PROMOTABLE_EVEN_VTABLE` or `PROMOTABLE_ODD_VTABLE`.

I understand the code now. Using Relaxed here works fine. Thank you for your response.
