### ISSUE TITLE
BytesMut::advance no longer advances cursor

### ISSUE THREAD

**Issue by camshaft** [tokio-rs/bytes#725]
In #698, the behavior of `BytesMut::advance` was changed to clear the buffer instead of reduce capacity when the advanced count matched `remaining`. In s2n-quic, we rely on `advance` actually reducing `remaining` and have several data structures and trait impls that rely on this behavior:

* [buffer::reassembler::Slot](https://github.com/aws/s2n-quic/blob/072452ecb51710d302492aaea465a85c1b650d21/quic/s2n-quic-core/src/buffer/reassembler/slot.rs#L255)
* [impl buffer::reader::Storage for BytesMut](https://github.com/aws/s2n-quic/blob/072452ecb51710d302492aaea465a85c1b650d21/quic/s2n-quic-core/src/buffer/reader/storage/bytes.rs#L64)

In its current state, there's no longer an efficient way to actually reduce capacity of `BytesMut`, since the only other option is to call `split_to` and discard the result, which isn't great since you churn on reference counts, which is kind of the whole point of `advance`, as indicated by the `#[must_use]` attribute: `consider BytesMut::advance if you don't need the other half`.

My vote would be to revert this change.

**Comment by seanmonstar** [comment]
Is there a simple test we could add with a comment to make sure we don't change this behavior again?

**Comment by camshaft** [comment]
> Is there a simple test we could add with a comment to make sure we don't change this behavior again?

I can open a PR tomorrow if no one beats me to it

**Comment by Darksonn** [comment]
Yes please, that would be great.

**Comment by camshaft** [comment]
Opened https://github.com/tokio-rs/bytes/pull/728
