### ISSUE TITLE
Importing bytes breaks comparisons of &[u8] and &[u8;32] in existing code.

### ISSUE THREAD

**Issue by poszu** [tokio-rs/bytes#735]
Hi, I hit a weird issue. I'm unsure if it relates to the `bytes` crate or Rust. Simply adding `use bytes::Bytes;` in existing code breaks it like in the following example:

**Working code:**
playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3eb8988ab94f8a231b5ede8172c530c8
```rust
fn main() {
    let hash = Vec::<u8>::new();
    assert!(hash.as_slice() < &[0u8; 32]);
}
```

**Failing code:**
playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b9bc566615f1a7347803af789f80a83d
```rust
use bytes::Bytes;

fn main() {
    let hash = Vec::<u8>::new();
    assert!(hash.as_slice() < &[0u8; 32]);
}
```
The failure is:
```
error[E0277]: can't compare `[u8]` with `[u8; 32]`
 --> src/main.rs:7:29
  |
7 |     assert!(hash.as_slice() < &[0u8; 32]);
  |                             ^ no implementation for `[u8] < [u8; 32]` and `[u8] > [u8; 32]`
  |
  = help: the trait `PartialOrd<[u8; 32]>` is not implemented for `[u8]`, which is required by `&[u8]: PartialOrd<&[u8; 32]>`
  = help: the following other types implement trait `PartialOrd<Rhs>`:
            `&[u8]` implements `PartialOrd<BytesMut>`
            `&[u8]` implements `PartialOrd<bytes::Bytes>`
            `[u8]` implements `PartialOrd<BytesMut>`
            `[u8]` implements `PartialOrd<bytes::Bytes>`
  = note: required for `&[u8]` to implement `PartialOrd<&[u8; 32]>`
```

Could you help me understand what is going on there?

**Comment by seanmonstar** [comment]
The `Bytes` type also implements `PartialEq`. Seems like the additional possible impls loaded make the compiler incapable of noticing there's a valid one to pick if it does type coercion.

You could choose to file an issue on the compiler.

**Comment by poszu** [comment]
Thanks @seanmonstar
