### ISSUE TITLE
Add support for zerocopy trait impls

### ISSUE THREAD

**Issue by joshlf** [tokio-rs/bytes#738]
An implementation is prototyped [here](https://github.com/joshlf/bytes/tree/zerocopy).

The proposal is to implement zerocopy's `ByteSlice` and `SplitByteSlice` traits for bytes' `Bytes` and `BytesMut` types, which will permit users to use `Bytes` and `BytesMut` with zerocopy features as requested in https://github.com/google/zerocopy/issues/1444.

Note that it's not possible for zerocopy to add these impls itself since the traits have safety invariants which are not guaranteed by `Bytes` and `BytesMut`'s public documentation - it's only possible to prove that these impls are correct *inside* of bytes itself.

**Comment by Darksonn** [comment]
The bytes crate is intended to never have a 2.0 release, so I'm reluctant to add new dependencies that don't have a similar guarantee.

What guarantees are missing? We may be able to guarantee the missing guarantees.

**Comment by Darksonn** [comment]
As an aside, it looks like the safety requirements of `SplitByteSlice` are *not* true for the `Bytes` or `BytesMut` types, as the address may not have the right value for zero-length slices.

**Comment by seanmonstar** [comment]
I have the same reservations as Alice. We've been very picky about adding any public dependencies.

**Comment by joshlf** [comment]
> What guarantees are missing? We may be able to guarantee the missing guarantees.

The main ones are the safety preconditions for [`ByteSlice`](https://docs.rs/zerocopy/0.8.5/zerocopy/byte_slice/trait.ByteSlice.html) and [`SplitByteSlice`](https://docs.rs/zerocopy/0.8.5/zerocopy/byte_slice/trait.SplitByteSlice.html).

> As an aside, it looks like the safety requirements of `SplitByteSlice` are _not_ true for the `Bytes` or `BytesMut` types, as the address may not have the right value for zero-length slices.

What do you mean by "not have the right value"?

**Comment by Darksonn** [comment]
I mean that with the implementation in your prototype, calling `split_at(0)` will return `Bytes::new()` as `first`, which means that the address of the zero-length slice returned by `Deref` may not be the same as the base address used by the original `Bytes` object that got split.

**Comment by joshlf** [comment]
Gotcha. That may be a non-starter then - we rely on the stability property to guarantee that if we first perform an alignment/size check and then split, the alignment and size will be the same after the split as before. It might be possible to work around (it would *not* be possible if you were saying that calling `deref` could change the address/length, but it doesn't sound like that's the case), but I'd need to confirm that we could shift the order in which we perform validation, and in any case it might pessimize things to have to unconditionally split before checking. It'd probably also result in very surprising behavior for callers if they validate alignment first and then call a method they expect to succeed (in fairness, who is doing that for ZSTs? Probably nobody).

**Comment by seanmonstar** [comment]
Mostly that if a split results in a 0-length slice of `Bytes`, we return `Bytes::new()`, which will be a different address than the actual bytes: https://github.com/tokio-rs/bytes/blob/d7c1d658d90c922eeee1dbc29bc6f6fd9a1a1a66/src/bytes.rs#L138

**Comment by Darksonn** [comment]
We can probably change `split_off` to return a static `Bytes` at the right address.

**Comment by joshlf** [comment]
That'd be great if it's on the table!

**Comment by Darksonn** [comment]
Is there anything else you need us to guarantee?

**Comment by joshlf** [comment]
It sounds like `Bytes` and `BytesMut` already guarantee what we need (when combined with #740). Take a skim and see if there's anything I've missed? I'm pretty sure these are satisfied.

[`ByteSlice` safety requirements](https://docs.rs/zerocopy/0.8.6/zerocopy/byte_slice/trait.ByteSlice.html#safety):

![Screenshot 2024-10-16 at 5 53 25 PM](https://github.com/user-attachments/assets/0e1b8950-69c7-434a-9e83-e733cfe31f3b)

[`SplitByteSlice` safety requirements](https://docs.rs/zerocopy/0.8.6/zerocopy/byte_slice/trait.SplitByteSlice.html#safety):

![Screenshot 2024-10-16 at 5 54 19 PM](https://github.com/user-attachments/assets/7ff4ab66-8dba-46a3-8712-e2abeac717e2)

**Comment by Darksonn** [comment]
That looks okay to me.

**Comment by joshlf** [comment]
Great! Then as soon as #740 is published on crates.io, we can add a feature to support bytes.
