### ISSUE TITLE
`io::Cursor` is a bit out of place

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/bytes#75]
I think this may not wish to use `io::Cursor` pervasively. This use case doesn't have much to do with `std::io`. The std version also [stores a ](https://github.com/rust-lang/rust/blob/0aeb9c12979e6da753701a798d04105b6b1a8c28/src/libstd/io/cursor.rs#L86) `u64` which isn't needed for `bytes`'s use case I believe.

**Comment by alexcrichton** [comment]
I also just twitch a bit whenever I see `io::Cursor`, I sort of regret adding it to std, it doesn't seem to really pull its weight.

**Comment by carllerche** [comment]
Makes sense. I mostly opted for `Cursor` to not add another type.

Another option would be to bring back `ByteBuf` or something like that?

**Comment by alexcrichton** [comment]
I think a local "cursor type" (w/e the name) may be right here, but I wouldn't add it just yet (I don't know what it should look like)

**Comment by est31** [comment]
> I also just twitch a bit whenever I see io::Cursor, I sort of regret adding it to std, it doesn't seem to really pull its weight.

A bit off topic, but note that I love it being in std, you can easily use it to Read over a buffer. Very interesting when you only offer a `io::Read` based API and people want to use it with their memory buffered data (best use case is tests).

**Comment by carllerche** [comment]
Using `Cursor` here is definitely a mistake on my part...

`std` implements `Read` and `Write` for `&[u8]` and `&mut [u8]` respectively. We probably want to follow that pattern and implement `Buf` / `BufMut` for `&[u8]` and `&mut [u8]`.

**Comment by tarcieri** [comment]
+1 on this. `io::Cursor` complicates `no_std` usage. I had to vendor it in to my PR to add `no_std` support: #135

Perhaps I should change that PR to just stop using `io::Cursor` entirely?

**Comment by tarcieri** [comment]
I opened a PR which vendors `std::io::Cursor` as `buf::Cursor` here (while also reducing the position counter size to `u32`):

https://github.com/carllerche/bytes/pull/146

I'm not sure that's entirely ideal but I don't see any other path forward here. I need something like it to make progress on #135

**Comment by seanmonstar** [comment]
So to clarify what will happen in v0.5:

- `impl Buf for Bytes` directly (remove `IntoBuf` of `Cursor<Self>`)
- `impl Buf for BytesMut` directly (remove `IntoBuf` of `Cursor<Self>`)
- `impl IntoBuf for &Bytes` to return `&[u8]`
- `impl IntoBuf for &BytesMut` to return `&[u8]`
- `impl IntoIterator for Bytes` to use `slice::Iter`
- `impl IntoIterator for BytesMut` to use `vec::IntoIter`

Look right?

**Comment by carllerche** [comment]
Looks bout right.

**Comment by YetAnotherMinion** [comment]
I am looking at implementing `IntoBuf` for `BytesMut`, to solve the tokio-io problem. I am trying to understand what needs to happen 

Am I reading the issues correctly that you want to get rid of Cursor. Does the replacement implementation you have in mind look like adding a position field to `Bytes` and `BytesMut` structs?

**Comment by YetAnotherMinion** [comment]
Never mind, I think I figured out how to do it using the fields of `Inner`.

The only problem I ran into is the removal of `set_position`. My understanding is that using only the elements of `Inner`, advancing the buffer would either be permanent or affect all copies. Is the ability to seek backwards used by anyone?.
