### ISSUE TITLE
BytesMut lacks an implementation of std::io::Write

### ISSUE THREAD

**Issue by NeoLegends** [tokio-rs/bytes#77]
Copied from https://github.com/tokio-rs/tokio-io/issues/28

>I'm currently using the codec module to implement a framed tansport.
>
>Before the refactoring, the encode-method of the old Codec trait received a Vec<u8> as parameter to serialize the message into. Vec<u8> directly implements std::io::Write which makes it very easy to put any kind of data into it, since most implementations have some way of writing into an instance of Write.
>
>Now the Vec<u8> has been replaced by BytesMut, which lacks a direct implementation of that trait. Write-compatibility is only archievable through into_writer, which consumes the BytesMut. Consuming is not possible, though, because the method only receives the BytesMut by &mut.
>
>Is this desired behavior?

**Comment by carllerche** [comment]
This seems fine to me. My only question is if `BytesMut` should grow as needed or return an error when it is full.

Thoughts @alexcrichton

**Comment by alexcrichton** [comment]
Sounds like a good idea to me! I'd grow the buffer internally

**Comment by carllerche** [comment]
@alexcrichton So BufMut has a writer adapter: BufMut::writer(). That implementation does not grow the buffer. It's built on BufMut::bytes_mut and remaining_mut.

**Comment by vorner** [comment]
I don't think a writer that doesn't grow the buffer is of much use. Usually, when I need a writer, I delegate the encoding or writing to some other code. And often I don't know in advance how much such code will write.

An example of code that would make sense:

```rust
use serde_cbor;
use tokio_io::io::Encoder;

struct E;

impl Encoder for E {
  ...
  fn encode(&mut self, item: Self::Item, dst: &mut BytesMut) -> Result<(), Self::Error> {
    serde_cbor::to_writer(dst)
  }
}
```

Now I have to wrap `dst` into a newtype that implements writer because it doesn't know how to be a writer (which isn't much work). If it didn't extend the `dst` as needed, I'd still need to wrap it, because I don't know the size in advance.

**Comment by carllerche** [comment]
This is now done: https://docs.rs/bytes/0.5.6/bytes/struct.BytesMut.html#impl-Write

**Comment by ColinFinck** [comment]
@carllerche `BytesMut` still lacks an implementation of `std::io::Write`.
What your URL refers to is an implementation of `std::fmt::Write`, which is something different.

I'd say this issue is still unresolved.

**Comment by taiki-e** [comment]
@ColinFinck please see https://github.com/tokio-rs/bytes/pull/478

**Comment by ColinFinck** [comment]
Thanks for the reference, @taiki-e 
In the meantime, I'm using `BufMut::writer` on `BytesMut`.
