### ISSUE TITLE
BytesMut's BufMut impl is much slower than Vec's

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/bytes#81]
Currently, it is ~2x slower. A cursory investigation reveals that there are way too many `is_inline` checks. Removing them brings the impls back on par.

**Comment by mzabaluev** [comment]
Could branching between _four_ different possible representations be a potential handicap as well?
I remember the times when small size optimization for `Vec`/`String` [was discussed](https://internals.rust-lang.org/t/small-string-optimization-remove-as-mut-vec/1320/16); the conclusion from people who tried to do this and measured the performance impact on rustc was that the added branching everywhere was just not worth it with the allocator that was in use (jemalloc was the default back then). I realise that the atomic memory barriers may be more costly, so a non-shared representation variant may still be worth it; not being much involved in this project's history, I can only assume that the other representations have shown performance improvement in realistic use cases.

I think a more promising direction for optimization would be to cut down on mutating APIs to optimize the primary use case for `bytes`, which is basically covered by the API of `Buf`/`BufMut` plus `BytesMut::reserve`: repetitions of pulling data incrementally into a `BytesMut` in a single task and handing off complete chunks in `Bytes` for potentially shared processing that does not tend to modify the data in place. I believe instilling some usage discipline can significantly reduce overhead on the hot paths.

If extension API on `Bytes` and segmentation of `BytesMut` is removed, the internal representation of `BytesMut` could just own a `Shared` instance referenced by immutable `Bytes` views (those which are in the ARC form) and never need to touch the reference count until it's dropped. `Bytes` would not need the capacity member so the struct would be 3/4 the size. It would still be possible to convert `Bytes` into `BytesMut` with no copying in case the `Bytes`' reference to the buffer is unique.

I can put these reformist ideas in more detail in an RFC-like issue if there is interest in this direction from the development team.

**Comment by carllerche** [comment]
@mzabaluev Sure, more details would be needed to consider the change:

- List of APIs added / removed.
- Changes to internals.
- Performance characteristic differences for common usage patterns of `Bytes` / `BytesMut`.

**Comment by mzabaluev** [comment]
I've done my homework in #268.
